'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_1399806385() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_1399806385", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_13998063851() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_13998063851", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_3029579_poster_p_1_3029579_who_needs_business_school_the_hidden_startup_resources_at_your_local_library() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_3029579-poster-p"& _ 
                        "-1-3029579-who-needs-business-school-the-hidden-startup-resources-at-your-local-"& _ 
                        "library", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_650_REL_graphic_568x233_workforcetools_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_650_REL_graphic_"& _ 
                        "568x233_workforcetools_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_c_kilpatrick2012_7861() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_c_kilpatrick2012"& _ 
                        "-7861", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_c_kilpatrick2012_78611() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_c_kilpatrick2012"& _ 
                        "-78611", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_dsc_9179() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_dsc_9179", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_dsc_91791() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_dsc_91791", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_imagesKNA0KKBR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_imagesKNA0KKBR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_imagesKNA0KKBR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_imagesKNA0KKBR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_imagesQFHE192F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_imagesQFHE192F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_library() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_library", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_library_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_library(1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_library_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_library(1)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_library_lending() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_library_lending", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_library_management_system_c_project() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_library-manageme"& _ 
                        "nt-system-c-project", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_library_management_system_c_project1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_library-manageme"& _ 
                        "nt-system-c-project1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_library_management_system_c_project2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_library-manageme"& _ 
                        "nt-system-c-project2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_Library1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_Library1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_Library11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_Library11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_Library5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_Library5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_librarymanagementsystem_140129095912_phpapp01_thumbnail_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_librarymanagemen"& _ 
                        "tsystem-140129095912-phpapp01-thumbnail-4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
